### ISSUE TITLE
aucune donnée affichée par le mod après réinstallation du serveur en v3.3.7

### ISSUE THREAD

**Issue by cooltk** [OGSteam/mod-expedition#12]
Le mod fonctionnait très bien en version 3.3.6

Les messages sont correctement remontés par xtense (croix vertes) mais les tables restent désespérément vides.

**Comment by Roms0406** [comment]
Salut, 

Peux tu essayer de préciser un peu stp

Ci joint un screen d'ogspy en v3.3.7 pour le mod expé fonctionnel (à 99% je suis toujours sur le bug des attaques ^^ )
![Sans titre](https://user-images.githubusercontent.com/25012902/79274005-2775f680-7ea4-11ea-8ccb-f2b109df9109.png)

**Comment by cooltk** [comment]
merci pour ta réponse rapide. Effectivement il fonctionnait bien chez toi. J'ai cherché chez moi du coup.
J'ai vérifié que le mod était bien reconnu par xtense, ce qui était le cas. MAis apr acquis de conscience, j'ai relancé l'installation des appels et ca a réglé mon problème. Merci pour la réponse.
![image](https://user-images.githubusercontent.com/19806448/79275558-b3891d80-7ea6-11ea-9fda-71485f284938.png)
